#!/usr/bin/env python3
"""
Generate release notes and known issues on every CI run.
Called by ci.yml after a successful test run on main.

Env vars (set by GitHub Actions):
  GH_TOKEN   — GitHub token for API calls
  GH_REPO    — owner/repo (e.g. hcdierks/quip-export)
  DEPLOY_SHA — current commit SHA
"""
import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent

# ── Helpers ──────────────────────────────────────────────────────────────────

def run(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, text=True).strip()


def run_safe(cmd: list[str], default: str = "") -> str:
    try:
        return subprocess.check_output(cmd, text=True, stderr=subprocess.DEVNULL).strip()
    except subprocess.CalledProcessError:
        return default


def gh_api(path: str) -> list:
    token = os.environ.get("GH_TOKEN", "")
    repo  = os.environ.get("GH_REPO", "")
    url   = f"https://api.github.com/repos/{repo}{path}"
    req   = urllib.request.Request(url, headers={
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    })
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.URLError:
        return []


# ── Collect data ─────────────────────────────────────────────────────────────

sha       = os.environ.get("DEPLOY_SHA") or run(["git", "rev-parse", "HEAD"])
short_sha = sha[:7]
timestamp = datetime.now(timezone.utc).isoformat()
repo      = os.environ.get("GH_REPO", "hcdierks/quip-export")

try:
    prev_tag  = run_safe(["git", "describe", "--tags", "--abbrev=0", "HEAD^"])
    git_range = f"{prev_tag}..HEAD" if prev_tag else "HEAD"
    commit_log = run(["git", "log", git_range, "--pretty=format:- %s (%h)", "--no-merges"])
except subprocess.CalledProcessError:
    commit_log = run(["git", "log", "-20", "--pretty=format:- %s (%h)", "--no-merges"])

try:
    result = subprocess.run(["make", "test"], capture_output=True, text=True)
    test_output = "\n".join((result.stdout + result.stderr).splitlines()[-3:])
except subprocess.CalledProcessError:
    test_output = "see CI log"

open_bugs    = gh_api("/issues?state=open&labels=bug&per_page=50")
open_sec     = gh_api("/issues?state=open&labels=security&per_page=50")
bug_lines    = [f"- [#{i['number']}]({i['html_url']}) {i['title']}" for i in open_bugs]
sec_lines    = [f"- [#{i['number']}]({i['html_url']}) {i['title']}"
                for i in open_sec if not i["title"].startswith("[parking-lot]")]

# ── Release notes ─────────────────────────────────────────────────────────────

release_date     = timestamp[:10]
release_filename = f"RELEASE-{release_date}-{short_sha}.md"
issues_summary   = (
    "\n".join(bug_lines + sec_lines)
    if bug_lines or sec_lines
    else f"_No known issues as of {timestamp}._"
)

release_notes = f"""# Release {short_sha} — {release_date}

| Field | Value |
|---|---|
| **Run** | {timestamp} |
| **Commit** | [`{short_sha}`](https://github.com/{repo}/commit/{sha}) |
| **Tests** | {test_output} |
| **Security (SAST)** | Semgrep + pip-audit — see SAST workflow |
| **Security (DAST)** | Not applicable — CLI tool, no network service |

## Changes in this release

{commit_log or "_No changes recorded._"}

## Security status

- SAST: Semgrep (p/python, p/owasp-top-ten, p/secrets) + pip-audit run on every push.
- DAST: Not applicable. This is a CLI tool with no network-accessible service endpoint.

## Known issues

{issues_summary}
"""

(ROOT / "docs/release-notes").mkdir(parents=True, exist_ok=True)
(ROOT / "docs/release-notes" / release_filename).write_text(release_notes)
(ROOT / "docs/release-notes/LATEST.md").write_text(release_notes)
print(f"Release notes written: docs/release-notes/{release_filename}")

# ── Known issues ──────────────────────────────────────────────────────────────

if not bug_lines and not sec_lines:
    body = f"✅ No known issues as of {timestamp}."
else:
    sections = []
    if bug_lines:
        sections.append("## Bugs\n\n" + "\n".join(bug_lines))
    if sec_lines:
        sections.append("## Open security findings\n\n" + "\n".join(sec_lines))
    body = "\n\n".join(sections)

known_issues = f"""# Known Issues

_Last updated: {timestamp} — commit `{short_sha}`_

{body}

_Auto-generated by CI on every run. To report an issue, open a GitHub issue with the `bug` label._
"""

(ROOT / "docs/known-issues.md").write_text(known_issues)
print("Known issues written: docs/known-issues.md")

# ── Update README ─────────────────────────────────────────────────────────────

readme_path = ROOT / "README.md"
readme = readme_path.read_text()

recent = "\n".join(commit_log.splitlines()[:5])

latest_section = f"""## Latest release

<!-- release-notes:start -->
**{short_sha}** — {timestamp}

{recent}

[Full release notes](docs/release-notes/LATEST.md) · [All releases](docs/release-notes/)
<!-- release-notes:end -->"""

issues_preview = (
    "\n".join((bug_lines + sec_lines)[:5])
    if bug_lines or sec_lines
    else f"✅ No known issues as of {timestamp}."
)
issues_section = f"""## Known issues

<!-- known-issues:start -->
{issues_preview}

[Full known issues list](docs/known-issues.md)
<!-- known-issues:end -->"""

if "<!-- release-notes:start -->" in readme:
    readme = re.sub(
        r"## Latest release\n<!-- release-notes:start -->.*?<!-- release-notes:end -->",
        latest_section, readme, flags=re.DOTALL
    )
else:
    readme += "\n" + latest_section

if "<!-- known-issues:start -->" in readme:
    readme = re.sub(
        r"## Known issues\n<!-- known-issues:start -->.*?<!-- known-issues:end -->",
        issues_section, readme, flags=re.DOTALL
    )
else:
    readme += "\n" + issues_section

readme_path.write_text(readme)
print("README.md updated")
